version: '3'

# in production, frontend is served from the node image
services:
  backend:
    restart: always
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "marcosraimondi1/multiapp-backend"
    ports:
      - "80:5000"